### ISSUE TITLE
Error evaluating flake with nixpkgs-unfree, `writeScriptBin` cannot be found.

### ISSUE THREAD

**Issue by r-vdp** [numtide/nixpkgs-unfree#12]
**Describe the bug**

See
https://gist.github.com/R-VdP/5f9f86b676e527ff51e4049b7cca0f09

This basic flake fails to evaluate, claiming that `pkgs.writeScriptBin` cannot be found. Using `github:nixos/nixpkgs/nixos-unstable` as input instead, does not cause this issue.

**To Reproduce**

nixos-rebuild the flake in the gist above.

**Expected behavior**

Flake evaluates successfully.

**System information**

NixOS unstable.

**Comment by zimbatm** [comment]
This will be fixed by https://github.com/cachix/devenv/pull/193
