### ISSUE TITLE
error: invalid flake input path element 'github:NixOS'

### ISSUE THREAD

**Issue by jdheyburn** [numtide/nixpkgs-unfree#23]
**Describe the bug**

I seem to get the below when trying to follow the steps outlined [here](https://github.com/numtide/nixpkgs-unfree#flake-usage).

```
error: invalid flake input path element 'github:NixOS'
```

**To Reproduce**

1. Follow the [Flake usage steps](https://github.com/numtide/nixpkgs-unfree#flake-usage)

**Expected behavior**

For there to be no error message

**System information**

On all my devices, NixOS and non-NixOS

**Additional context**

**Comment by zimbatm** [comment]
thanks, I pushed a fix to the example
